# Generated by Django 4.2 on 2024-10-21 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonapp', '0004_alter_order_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='trac_no',
        ),
    ]
