# Generated by Django 4.2 on 2024-10-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonapp', '0005_remove_order_trac_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
