# Generated by Django 4.2 on 2024-10-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonapp', '0006_remove_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='fname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='lname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='pin',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=150),
        ),
    ]
